[versions]
sdk-min = "19"
sdk-target = "31"

kotlin = "1.9.0"
android-plugin = "7.4.2"

coroutines = "1.7.3"
dagger = "2.47"
espresso = "3.5.1"
jackson = "2.15.2"
lifecycle = "2.5.1" # 2.6.1
navigation = "2.5.3"
room = "2.4.3" # 2.5.1
tox4j-android = "0.2.18"
tox4j-core = "0.2.3"

[plugins]
versions = "com.github.ben-manes.versions:0.47.0"
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "android-plugin" }
androidLibrary = { id = "com.android.library", version.ref = "android-plugin" }

[libraries]
androidx-activity = "androidx.activity:activity:1.5.1" # 1.7.2
androidx-appcompat = "androidx.appcompat:appcompat:1.4.2" # 1.6.1
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core-ktx = "androidx.core:core-ktx:1.8.0" # 1.10.1
androidx-fragment = "androidx.fragment:fragment:1.5.7"

androidx-multidex = "androidx.multidex:multidex:2.0.1"
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }
androidx-preference = "androidx.preference:preference:1.2.0"

androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

google-android-material = "com.google.android.material:material:1.5.0" # 1.7.0
google-dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
google-dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger" }

jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }

javax-inject = "javax.inject:javax.inject:1"

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

nayuki-qrcodegen = "io.nayuki:qrcodegen:1.8.0"

square-leakcanary = "com.squareup.leakcanary:leakcanary-android:2.12"

coil = "io.coil-kt:coil:1.4.0"

tox4j-android-aarch64 = { module = "org.toktok:tox4j-c_aarch64-linux-android", version.ref = "tox4j-android" }
tox4j-android-arm = { module = "org.toktok:tox4j-c_armv7a-linux-androideabi", version.ref = "tox4j-android" }
tox4j-android-i686 = { module = "org.toktok:tox4j-c_i686-linux-android", version.ref = "tox4j-android" }
tox4j-android-amd64 = { module = "org.toktok:tox4j-c_x86_64-linux-android", version.ref = "tox4j-android" }
tox4j-api = { module = "org.toktok:tox4j-api_2.11", version.ref = "tox4j-core" }
tox4j-c = { module = "org.toktok:tox4j-c_2.11", version.ref = "tox4j-core" }

test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
test-junit-ext = "androidx.test.ext:junit:1.1.5"
test-rules = "androidx.test:rules:1.5.0"
test-runner = "androidx.test:runner:1.5.2"

# Google's very impressive workaround for the following error:
# Duplicate class com.google.common.util.concurrent.ListenableFuture found
# in modules jetified-guava-19.0 (com.google.guava:guava:19.0) and
# jetified-listenablefuture-1.0 (com.google.guava:listenablefuture:1.0)
google-guava-workaround = "com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava"

[bundles]
